# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Model.py
# Created on: 2016-03-28 23:42:24.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
basin = "basin"
floodzones = "floodzones"
floodzones_Clip1_shp = "D:\\BOOKS\\GISen\\_PYTHON\\Python Scripting for ArcGIS\\SF_Exercise\\Exercise02\\Results\\floodzones_Clip1.shp"
floodzones_Clip1_Select_shp = "D:\\BOOKS\\GISen\\_PYTHON\\Python Scripting for ArcGIS\\SF_Exercise\\Exercise02\\Results\\floodzones_Clip1_Select.shp"

# Process: Clip
arcpy.Clip_analysis(floodzones, basin, floodzones_Clip1_shp, "")

# Process: Select
arcpy.Select_analysis(floodzones_Clip1_shp, floodzones_Clip1_Select_shp, "\"SFHA\" = 'IN'")

