# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# buffer.py
# Created on: 20xx-05-22 12:17:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
inputFeatures = "C:\\gispy\\data\\ch05\\park.shp"
distance = "100 Feet"
outputFeatures = "C:\\gispy\\data\\ch05\\park_Buffer.shp"

# Process: Buffer
arcpy.Buffer_analysis(inputFeatures, outputFeatures, distance, "FULL", "ROUND", "NONE", "")




