# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# buffer2.py
# Created on: 2016-04-18 15:28:48.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
park = "park"
Distance__value_or_field_ = "100 Feet"
Output_Feature_Class = "C:\\Users\\AaronHsu\\Documents\\ArcGIS\\Default.gdb\\park_Buffer"

# Process: Buffer
arcpy.Buffer_analysis(park, Output_Feature_Class, Distance__value_or_field_, "FULL", "ROUND", "NONE", "")

