# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# script1.py
# Created on: 2016-08-02 12:30:18.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: script1 <input> <output> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
input = arcpy.GetParameterAsText(0)
if input == '#' or not input:
    input = "D:\\BOOKS\\GISen\\_PYTHON\\PythonForArcGIS\\SF_PFA\\ch06\\data\\getty_rast" # provide a default value if unspecified

output = arcpy.GetParameterAsText(1)
if output == '#' or not output:
    output = "D:\\BOOKS\\GISen\\_PYTHON\\PythonForArcGIS\\SF_PFA\\ch06\\scratch\\output.txt" # provide a default value if unspecified

# Local variables:

# Process: Raster to ASCII
arcpy.RasterToASCII_conversion(input, output)

