# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# script3.py
# Created on: 2016-08-02 12:32:42.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: script3 <input> <output> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
input = arcpy.GetParameterAsText(0)

output = arcpy.GetParameterAsText(1)

# Local variables:

# Process: Raster to ASCII
arcpy.RasterToASCII_conversion(input, output)

